version: "3.8"

services:
  # PostgreSQL service
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mentri
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # MinIO service
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

  # Node.js backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:admin@postgres:5432/mentri?schema=public"
      JWT_SECRET: eyJhbGciOiJIUzI1NiJ9
      JWT_EXPIRES_IN: 1d
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_DOCUMENT_BUCKET: document
      MINIO_REPORT_BUCKET: report
      MINIO_USE_SSL: false
      APP_BASE_URL_DEV: http://localhost:3000
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
