services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sinar_frontend
    restart: always
    ports:
      - "127.0.0.1:5173:5173"
    env_file:
      - .env
    environment:
      - PORT=5173
      - HOST=0.0.0.0
      - ORIGIN=https://fe.sinerginarasi.site
    networks:
      - backend_sinar_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend_sinar_network:
    external: true