services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sinar_frontend
    restart: always
    ports:
      - "127.0.0.1:5173:5173"  # Port 5173
    environment:
      - NODE_ENV=production
      - PORT=5173
      - HOST=0.0.0.0
      - ORIGIN=https://fe.sinerginarasi.site
      - VITE_API_BASE_URL=https://be.sinerginarasi.site
      - VITE_API_TIMEOUT=30000
      - VITE_APP_NAME=SINAR Web Application
      - VITE_APP_VERSION=1.0.0
    networks:
      - backend_sinar_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend_sinar_network:
    external: true